### ISSUE TITLE
pointtofleek.io

### ISSUE THREAD

**Issue by jeffreylo** [jeffreylo/point-to-fleek#2]
This really ought to be a web-service.

Something like:

``` sh
$ curl -X POST -d "on point" https://pointtofleek.io
on fleek
```

**Comment by cmaron** [comment]
Sounds like a job for AWS Lambda

**Comment by jeffreylo** [comment]
@Cbeck527 or @jeffu might know a thing or two about this.

**Comment by cmaron** [comment]
I've done some work with it, though so far only in node. Python gets tricky due to how you package dependencies (at least this was the case a couple of months ago).

**Comment by jeffreylo** [comment]
Well, this project could leverage your node synergies since this is using some web-scale Chrome Javascript

**Comment by jeffu** [comment]
It's not bad for most python dependencies. Just do a `pip install module-name -t /path/to/project-dir` before you package the source to upload to lambda.

**Comment by jeffu** [comment]
Also, how committed are you to the `.io` TLD? It's expensive. Not `.best` expensive, but a cheaper TLD for a joke as a service might be better.

**Comment by Cbeck527** [comment]
Use [apex](http://apex.run), forget about annoying AWS console web pages.

**Comment by jeffreylo** [comment]
@cmaron what's the status of this issue

**Comment by cmaron** [comment]
Actually think we should consider a slack bot first @jeffreylo
